import type { Metadata } from "next";
import { Grechen_Fuemen, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const grechen = Grechen_Fuemen({
  variable: "--font-grechen-fuemen",
  weight: "400",
});
const lato = Lato({
  variable: "--font-lato",
  weight: "400",
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${grechen.variable} ${lato.variable} antialiased font-lato relative`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
