import type { Metadata } from "next";
import { Geist, Grechen_Fuemen, Rubik } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const grechen = Grechen_Fuemen({
  variable: "--font-grechen-fuemen",
  weight: "400",
});
const rubik = Rubik({
  variable: "--font-rubik",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Car Fácil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grechen.variable} ${geistSans.variable} ${rubik.variable} antialiased p-2`}
      >
        {children}
      </body>
    </html>
  );
}
